### ISSUE TITLE
TypeError: this.props.getEditor is not a function

### ISSUE THREAD

**Issue by finn1310** [stulip/react-native-pell-rich-editor#33]
<img width="365" alt="Screen Shot 2020-02-15 at 10 55 47" src="https://user-images.githubusercontent.com/47772671/74581415-c637c100-4fe1-11ea-8b27-07f0e827dd70.png">
<img width="582" alt="Screen Shot 2020-02-15 at 10 53 25" src="https://user-images.githubusercontent.com/47772671/74581390-8f61ab00-4fe1-11ea-903e-42726c76d9e3.png">
<img width="249" alt="Screen Shot 2020-02-15 at 10 53 51" src="https://user-images.githubusercontent.com/47772671/74581392-912b6e80-4fe1-11ea-870e-922df97ae064.png">

**Comment by finn1310** [comment]
> No description provided.

Issue has been fixed.

**Comment by catmans1** [comment]
@finn1310 
How did you fix it?

**Comment by finn1310** [comment]
> @finn1310
> How did you fix it?

I forgot to use '.current' for useRef hooks ReactJS.

**Comment by catmans1** [comment]
@finn1310 
I also use current, but it still happen error.
Could you share me the part code of that?

**Comment by finn1310** [comment]
@catmans1 
https://github.com/finn1310/News-ReactNative/blob/master/src/components/Profile/NewPost.js

**Comment by Nirav1432** [comment]
Main Issue is due to making "Ref" In Richtoolbar
Using this I Solved the Issue
So Put get editor as inline function in <RichToolbar> Like This "getEditor={() => this.richText}"


Example : -
<View>
                    <View style={styles.View3}>
                        <RichEditor
                            ref={x => this.richText = x}
                            placeholder={'please input content'}
                            style={{ flex: 1 }}
                            // initialContentHTML={initHTML}
                            // editorInitializedCallback={this.editorInitializedCallback}
                            onChange={(val) => console.log(val)}
                        // onHeightChange={that.handleHeightChange}
                        />
                    </View>

                    <RichToolbar
                        getEditor={() => this.richText}
                      />
</view>

**Comment by mohamed-ikram** [comment]
hello @Nirav by doing that it throws error in this.richText.current undefined
